project:
  type: website
  output-dir: docs

website:
  title: "Assessing Urban War Damage in Kharkiv and Mariupol, Ukraine Using Sentinel-1 Imagery"
  navbar:
    right:
      - text: "Open in GitHub"
        icon: github
        href: https://github.com/YUJIA-MA-UCL/SixQL.github.io
        
book:
  title: "CASA0025 Final Assessment"
  author: "SixQL"
  date: "15/04/2025"
  chapters:
    - index.qmd

  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  favicon: favicon.ico
  sidebar:
    logo: logo.png



format:
  html:
    theme:
      dark: darkly
      light: cosmo
    code-copy: true
    code-overflow: wrap
    highlight-style: monokai.theme
    linkcolor: "#34a832"
