project:
  type: website
  output-dir: docs

book:
  title: "CASA0025 Final Assessment"
  author: "SixQL"
  date: "11/04/2025"
  chapters:
    - index.qmd

  repo-actions: [edit]
  downloads: [pdf, epub]
  favicon: favicon.ico
  sidebar:
    logo: logo.png



format:
  html:
    theme:
      dark: darkly
      light: cosmo
    code-copy: true
    code-overflow: wrap
    highlight-style: monokai.theme
    linkcolor: "#34a832"
